language: emacs-lisp
sudo: false
before_install:
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install $EVM_EMACS --use
  - cp init.test.el init.el
  - INSECURE=1 YES=1 make install
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
script:
  - emacs --version
  - make test
