blank_issues_enabled: false
contact_links:
  - name: ğŸ“ Suggest or request a new feature
    url: https://github.com/orgs/doomemacs/discussions/new?category=ideas
  - name: ğŸ“ Ask for help from the community
    url: https://doomemacs.org/discuss/new?category=questions
  - name: ğŸ“ Request a pinned package be bumped
    url: https://github.com/orgs/doomemacs/discussions/new?category=re-modules&title=[Bump Request] &body=%23%23%23%20Packages%20to%20bump%0A%0A-%20PackageA%0A-%20PackageB%0A-%20PackageB%0A%0A%23%23%23%20Why%20should%20they%20be%20bumped%20outside%20of%20the%20typical%20bump%20schedule%3F%0A%0ABecause%20...%3F
  - name: ğŸ“£ Project news & announcements
    url: https://github.com/doomemacs/community/discussions/categories/announcements
  - name: Official Documentation
    url: https://docs.doomemacs.org
    about: "Also available from within Doom: `M-x doom/help`"
  # - name: Community Wiki
  #   url: https://wiki.doomemacs.org
  - name: Visit our Discussions board
    url: https://doomemacs.org/discuss
  - name: Visit our Discord server
    url: https://doomemacs.org/discord
  - name: All community resources
    url: https://github.com/doomemacs/?view_as=public
