name: Tests

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - '**.org'
      - 'docs/**'
      - '.dir-locals.el'
      - 'LICENSE'
    branches:
      - master

jobs:
  unix-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version: [27.1, 27.2, snapshot]
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Check out doom-emacs
        uses: actions/checkout@v2
      - name: Set up test Doom profile
        run:  bin/doom sync --profile test
      - name: Set up test Doom profile
        run:  bin/doom test
      - name: Cache package builds
        uses: actions/cache@v2
        with:
          path: .local/straight/repos
          key: ${{ runner.os }}-build-doom-packages-${{ hashFiles('**/packages.el') }}
          restore-keys: |
            ${{ runner.os }}-build-doom-packages-
      # FIXME
      # name: Compile
      #   run: "bin/doom -y compile"

  windows-test:
    runs-on: windows-latest
    strategy:
      matrix:
        emacs-version: [27.1, 27.2, snapshot]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - uses: jcs090218/setup-emacs-windows@master
        with:
          version: ${{ matrix.emacs-version }}
      - name: Set up test Doom profile
        run:  bin/doom sync --profile test
      - name: Set up test Doom profile
        run:  bin/doom test
      - name: Cache package builds
        uses: actions/cache@v2
        with:
          path: .local/straight/repos
          key: ${{ runner.os }}-build-doom-packages-${{ hashFiles('**/packages.el') }}
          restore-keys: |
            ${{ runner.os }}-build-doom-packages-
